#!/bin/bash

set -e

. $(dirname $0)/base

WORKDIR "/work/src"
RUN git clone https://gitlab.freedesktop.org/slirp/libslirp.git
WORKDIR "/work/src/libslirp"
RUN meson build --default-library both && ninja -C build install

